exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- submission.md

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Rome # Timezone for blog posts and alike

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/2019/assets/placeholder-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/2019/assets/placeholder-social.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Microservices 2019" # Site name or title, also used in jekyll-seo-tag
logo: "/2019/assets/images/microservices.svg" # Site logo, also used in jekyll-seo-tag
description: "Academia meets Industry" # Site description and default description, also used in jekyll-seo-tag
url: "/2019" # Site url, also used in jekyll-seo-tag
baseurl: "/2019" # Site url, also used in jekyll-seo-tag
email: "microservices@fh-dortmund.de"
avatarurl: "/2019/assets/images/favicon.ico" # Uses avatars for favicons to get multiple sites, eg Gravatar, Twitter, GitHub
header_left: |
  <a style="color:inherit; text-decoration: none !important;" href="/"><h2>
  <img style="width: 50px; padding-bottom: 5px;" src="/2019/assets/images/microservices.svg" alt="">
  Microservices</h2></a>
header_right: |
  <ul style="list-style-type:none; margin:0; padding:0; overflow:hidden;">
    <li style="float:right;">
      <a style="display:block; color:inherit; text-decoration:none !important;" href="https://microservices.community/e/microservices2019">
        <img class="img-responsive" style="position:absolute; top:10px; z-index:10; right:5px; transform: rotate(25deg);" src="https://www.microservices.community/assets/images/badges/1-black.png" alt="Microservices Community Collaboration Badge">
      </a>
    </li>
    <li style="float:right; margin-right:138px;">
      <p style="margin-top:10px; margin-bottom:-5px;">Dortmund</p>
      <p>19-21 Feb. 2019</p>
    </li>
  </ul>
# 8. Site navigation
navigation_header:
  Home: /2019/
  Attending: /2019/attending/
  Keynotes: /2019/keynotes/
  Program: /2019/program/
  Photos: /2019/photos/
  Satellite Events: /2019/satellite/
  Social Events: /2019/social_event/
  Committees: /2019/committees/
  Registration: /2019/registration/
  Contact: /2019/contact/  
  Conference Series: /