# Event parameters ------------------------------------------------------------
edition: 2019
title: Microservices 2019
baseurl: /2019
header:
  city: "Dortmund"
  dates: "19-21 Feb. 2019"
email: "microservices@fh-dortmund.de"
description: "Academia meets Industry"
timezone: Europe/Rome
# twitter_feed: c_microservices 
# legal_notice_url: /legal-notice
community_badge:
  asset: "1-black.png"
  token: "microservices2019"

# Site navigation -------------------------------------------------------------
navigation_header:
  Home:              /
  Attending:         /attending/
  Keynotes:          /keynotes/
  Program:           /program/
  Photos:            /photos/
  Satellite Events:  /satellite/
  Social Events:     /social_event/
  Committees:        /committees/
# Registration:      /registration/
# Sponsoring:        /sponsors/
# Contact:           /contact/  

# Exclude from build -----------------------------------------------------------
exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- submission.md

#------------------------------------------------------------------------------
logo: "/assets/images/microservices.svg"
url: "https://conf-micro.services/"
avatarurl: "/assets/images/favicon.ico"

encoding: utf-8

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-email-protect

sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/2019/assets/placeholder-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/2019/assets/placeholder-social.png" # Default image for sharing